import Foundation

enum AccessibilityID {
    static let mainViewRoot = "mainViewRoot"
    static let mainContentScrollView = "mainContentScrollView"
    static let apodMediaSection = "apodMediaSection"
    static let apodDetailsSection = "apodDetailsSection"
    static let apodProvenanceSection = "apodProvenanceSection"
    static let apodSourceSection = "apodSourceSection"
    static let shareAPODButton = "shareAPODButton"
    static let shareSection = "shareSection"
    static let refreshAPODButton = "refreshAPODButton"
    static let randomAPODButton = "randomAPODButton"
    static let openArchiveButton = "openArchiveButton"
    static let toggleAppearanceButton = "toggleAppearanceButton"
    static let openSettingsButton = "openSettingsButton"
    static let openFavoritesButton = "openFavoritesButton"
    static let jumpToLatestAPODDateButton = "jumpToLatestAPODDateButton"
    static let previousAPODDateButton = "previousAPODDateButton"
    static let nextAPODDateButton = "nextAPODDateButton"
    static let apiRequestLoadingState = "apiRequestLoadingState"
    static let apiRequestFailureState = "apiRequestFailureState"
    static let apiOfflineBanner = "apiOfflineBanner"
    static let apiRateLimitBanner = "apiRateLimitBanner"
    static let apiKeyBanner = "apiKeyBanner"
    static let apiSyncBanner = "apiSyncBanner"
    static let apiErrorBanner = "apiErrorBanner"
    static let apodTitleText = "apodTitleText"
    static let apodDateText = "apodDateText"
    static let apodCreditText = "apodCreditText"
    static let apodExplanationText = "apodExplanationText"
    static let apodExplanationToggleButton = "apodExplanationToggleButton"
    static let favoriteAPODButton = "favoriteAPODButton"
    static let openNasaPageButton = "openNasaPageButton"
    static let openPreferredMediaButton = "openPreferredMediaButton"
    static let favoritesSheetRoot = "favoritesSheetRoot"
    static let favoritesEmptyState = "favoritesEmptyState"
    static let favoritesDoneButton = "favoritesDoneButton"
    static let favoritesSearchField = "favoritesSearchField"
    static let archiveSheetRoot = "archiveSheetRoot"
    static let archiveSearchField = "archiveSearchField"
    static let archiveEmptyState = "archiveEmptyState"
    static let archiveLoadMoreButton = "archiveLoadMoreButton"
    static let settingsSheetRoot = "settingsSheetRoot"
    static let settingsCloseButton = "settingsCloseButton"
    static let followSystemAppearanceToggle = "followSystemAppearanceToggle"
    static let darkModeToggle = "darkModeToggle"
    static let dataSaverModeToggle = "dataSaverModeToggle"
    static let preferHDImagesToggle = "preferHDImagesToggle"
    static let lastStatusCodeValue = "lastStatusCodeValue"
    static let networkConnectionValue = "networkConnectionValue"
    static let meteredNetworkValue = "meteredNetworkValue"
    static let lowDataModeValue = "lowDataModeValue"
    static let autoplayPolicyValue = "autoplayPolicyValue"
    static let networkEfficiencyValue = "networkEfficiencyValue"
    static let apodImageView = "apodImageView"
    static let apodImageUnavailableMessage = "apodImageUnavailableMessage"
    static let videoDisabledMessage = "videoDisabledMessage"
    static let directVideoPlayer = "directVideoPlayer"
    static let playVideoInAppButton = "playVideoInAppButton"
    static let openVideoExternalButton = "openVideoExternalButton"
    static let unsupportedVideoMessage = "unsupportedVideoMessage"
    static let videoAutoplayPausedBadge = "videoAutoplayPausedBadge"

    static func favoriteRowIdentifier(for nasa: NASA) -> String {
        "favoriteAPODRow-\(nasa.date ?? "unknown")"
    }

    static func favoriteDeleteActionIdentifier(for nasa: NASA) -> String {
        "favoriteAPODDelete-\(nasa.date ?? "unknown")"
    }

    static func archiveRowIdentifier(for nasa: NASA) -> String {
        "archiveAPODRow-\(nasa.date ?? "unknown")"
    }
}
